parameters:
#    back_card.example.class: Back\CardBundle\Example

services:
#    back_card.example:
#        class: %back_card.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
