<?php

namespace Proxies\__CG__\Front\WebsiteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClinicalSituation extends \Front\WebsiteBundle\Entity\ClinicalSituation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\ClinicalSituation' . "\0" . 'id', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\ClinicalSituation' . "\0" . 'name', 'cards', 'cards2', 'parent', 'clinicalSituations');
        }

        return array('__isInitialized__', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\ClinicalSituation' . "\0" . 'id', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\ClinicalSituation' . "\0" . 'name', 'cards', 'cards2', 'parent', 'clinicalSituations');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClinicalSituation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addCard(\Front\WebsiteBundle\Entity\Card $cards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCard', array($cards));

        return parent::addCard($cards);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCard(\Front\WebsiteBundle\Entity\Card $cards)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCard', array($cards));

        return parent::removeCard($cards);
    }

    /**
     * {@inheritDoc}
     */
    public function getCards()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCards', array());

        return parent::getCards();
    }

    /**
     * {@inheritDoc}
     */
    public function addCards2(\Front\WebsiteBundle\Entity\Card $cards2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCards2', array($cards2));

        return parent::addCards2($cards2);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCards2(\Front\WebsiteBundle\Entity\Card $cards2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCards2', array($cards2));

        return parent::removeCards2($cards2);
    }

    /**
     * {@inheritDoc}
     */
    public function getCards2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCards2', array());

        return parent::getCards2();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Front\WebsiteBundle\Entity\ClinicalSituation $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function addClinicalSituation(\Front\WebsiteBundle\Entity\ClinicalSituation $clinicalSituations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClinicalSituation', array($clinicalSituations));

        return parent::addClinicalSituation($clinicalSituations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClinicalSituation(\Front\WebsiteBundle\Entity\ClinicalSituation $clinicalSituations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClinicalSituation', array($clinicalSituations));

        return parent::removeClinicalSituation($clinicalSituations);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinicalSituations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinicalSituations', array());

        return parent::getClinicalSituations();
    }

}
