security:
    encoders:
        Back\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern:        ^/admin/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /admin/login/
            logout:
                path:       fos_user_security_logout
                target:     /admin
            remember_me:
                key:        %secret%
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: front_website_card
                check_path: front_website_card_admin
                always_use_default_target_path : true
                default_target_path: front_website_card_admin
            logout:
                path:       front_website_card_logout
                target:     /
            remember_me:
                key:        %secret%

    access_control:
        - { path: ^/admin$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/, roles: ROLE_ADMIN }
        - { path: ^/fiche/modifier/, roles: ROLE_USER }