parameters:
#    back_website.example.class: Back\WebsiteBundle\Example

services:
#    back_website.example:
#        class: %back_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
