<?php

namespace Front\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiotherapyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiotherapyRepository extends EntityRepository
{
}
