<?php

namespace Front\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClinicalSituationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicalSituationRepository extends EntityRepository
{
	public function getCSRoot()
	{
		$qb = $this->createQueryBuilder('cs')
			->where('cs.parent is NULL');
			
		return $qb;
	}
	
	public function getCSNoMe($id)
	{
		$qb = $this->createQueryBuilder('cs')
			->where('cs.id != '.$id);
			
		return $qb;
	}
}
