parameters:
#    back_text.example.class: Back\TextBundle\Example

services:
#    back_text.example:
#        class: %back_text.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
