parameters:
#    back_clinical_situation.example.class: Back\ClinicalSituationBundle\Example

services:
#    back_clinical_situation.example:
#        class: %back_clinical_situation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
