<?php

namespace Proxies\__CG__\Front\WebsiteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Card extends \Front\WebsiteBundle\Entity\Card implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'id', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'name', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textPatient', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textMDShort', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textMDFull', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textRef', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'createdTime', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'modifiedTime', 'biotherapy', 'clinicalSituation', 'clinicalSituation2', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'tags');
        }

        return array('__isInitialized__', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'id', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'name', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textPatient', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textMDShort', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textMDFull', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'textRef', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'createdTime', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'modifiedTime', 'biotherapy', 'clinicalSituation', 'clinicalSituation2', '' . "\0" . 'Front\\WebsiteBundle\\Entity\\Card' . "\0" . 'tags');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Card $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextPatient($textPatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextPatient', array($textPatient));

        return parent::setTextPatient($textPatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextPatient', array());

        return parent::getTextPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextMDShort($textMDShort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextMDShort', array($textMDShort));

        return parent::setTextMDShort($textMDShort);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextMDShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextMDShort', array());

        return parent::getTextMDShort();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextMDFull($textMDFull)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextMDFull', array($textMDFull));

        return parent::setTextMDFull($textMDFull);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextMDFull()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextMDFull', array());

        return parent::getTextMDFull();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiotherapy(\Front\WebsiteBundle\Entity\Biotherapy $biotherapy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiotherapy', array($biotherapy));

        return parent::setBiotherapy($biotherapy);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiotherapy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiotherapy', array());

        return parent::getBiotherapy();
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\Front\WebsiteBundle\Entity\Tag $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', array($tags));

        return parent::addTag($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\Front\WebsiteBundle\Entity\Tag $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', array($tags));

        return parent::removeTag($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(\Back\UserBundle\Entity\User $userCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', array($userCreated));

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', array());

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserModified(\Back\UserBundle\Entity\User $userModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserModified', array($userModified));

        return parent::setUserModified($userModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserModified', array());

        return parent::getUserModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedTime($createdTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedTime', array($createdTime));

        return parent::setCreatedTime($createdTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedTime', array());

        return parent::getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedTime($modifiedTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedTime', array($modifiedTime));

        return parent::setModifiedTime($modifiedTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedTime', array());

        return parent::getModifiedTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setClinicalSituation(\Front\WebsiteBundle\Entity\ClinicalSituation $clinicalSituation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinicalSituation', array($clinicalSituation));

        return parent::setClinicalSituation($clinicalSituation);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinicalSituation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinicalSituation', array());

        return parent::getClinicalSituation();
    }

    /**
     * {@inheritDoc}
     */
    public function setClinicalSituation2(\Front\WebsiteBundle\Entity\ClinicalSituation $clinicalSituation2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClinicalSituation2', array($clinicalSituation2));

        return parent::setClinicalSituation2($clinicalSituation2);
    }

    /**
     * {@inheritDoc}
     */
    public function getClinicalSituation2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClinicalSituation2', array());

        return parent::getClinicalSituation2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextRef($textRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextRef', array($textRef));

        return parent::setTextRef($textRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextRef', array());

        return parent::getTextRef();
    }

}
